"""
Recovery Proposal and Action Request models for TarkaRaksha.
Enforces the safety invariant:
AI outputs (proposals) are untrusted and advisory.
Action requests must undergo deterministic policy validation before execution.
Never direct execution from an AI proposal.
"""
from datetime import datetime
from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field, field_validator
from .enums import ActionType
from .money import Money


class RecoveryProposal(BaseModel):
    """
    Advisory proposal generated by the autonomous recovery agent in response to an MRDP.
    Strictly untrusted: represents an AI suggestion, NEVER an authorization.
    """
    proposal_id: str
    mrdp_id: str
    intent_id: str
    proposed_action: ActionType
    suggested_amount: Optional[Money] = None
    reasoning: str
    confidence: float = Field(default=0.8, ge=0.0, le=1.0)
    suggested_at: datetime
    model_identifier: Optional[str] = None
    parameters: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        strict=True,
    )

    @field_validator("suggested_at", mode="before")
    @classmethod
    def validate_timezone(cls, v: Any) -> datetime:
        if isinstance(v, str):
            dt = datetime.fromisoformat(v)
        elif isinstance(v, datetime):
            dt = v
        else:
            raise TypeError(f"Timestamp must be datetime or ISO string, got {type(v).__name__}")
        
        if dt.tzinfo is None:
            raise ValueError("suggested_at must be timezone-aware (e.g., UTC)")
        return dt


class ActionRequest(BaseModel):
    """
    Concrete action request derived from a recovery proposal or control room operator.
    Must pass deterministic rule validation and authorization bounds check before execution.
    """
    request_id: str
    intent_id: str
    action_type: ActionType
    amount: Optional[Money] = None
    target_reference: str  # e.g., payment_id, order_id
    idempotency_key: str
    requested_at: datetime
    requested_by: str  # e.g., "AI_RECOVERY_AGENT", "OPERATOR"
    proposal_reference: Optional[str] = None
    is_validated: bool = False
    validation_notes: Optional[str] = None

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        strict=True,
    )

    @field_validator("requested_at", mode="before")
    @classmethod
    def validate_timezone(cls, v: Any) -> datetime:
        if isinstance(v, str):
            dt = datetime.fromisoformat(v)
        elif isinstance(v, datetime):
            dt = v
        else:
            raise TypeError(f"Timestamp must be datetime or ISO string, got {type(v).__name__}")
        
        if dt.tzinfo is None:
            raise ValueError("requested_at must be timezone-aware (e.g., UTC)")
        return dt
